### ISSUE TITLE
Causes crash when making new world with Incendium, on Fabric 1.19.2

### ISSUE THREAD

**Issue by TalEdd** [alcatrazEscapee/cyanide#12] opened 2022-09-29 15:57 UTC
[crash-2022-09-29_23.55.43-client.txt](https://github.com/alcatrazEscapee/cyanide/files/9676314/crash-2022-09-29_23.55.43-client.txt)

Removing this mod, makes the world creation work fine.

**Comment by alcatrazEscapee** [comment] 2022-09-29 16:09
Duplicate of #5

**Closed as completed by alcatrazEscapee** 2022-09-29 16:09 UTC

**Comment by TalEdd** [comment] 2022-09-29 16:21
Noted, thank you!
